development:
  adapter: postgresql
  encoding: unicode
  database: teamtracker_dev
  pool: 10
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: teamtracker_test
  pool: 10
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: teamtracker_prod
  pool: 10
  username: postgres
  password:
